dist: xenial

language: rust

services:
  - docker

before_install:
  - docker -v

script:
  # Publish when using '[publish docker]' keywords
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1 | tr -d '\n')
  - if [[ ${COMMIT_MESSAGE} =~ "[publish docker]" ]]; then ./build-docker.sh && docker push zboxfs/android; fi;

notifications:
  email:
    on_success: never
